### ISSUE TITLE
Orange color display problem 

### ISSUE THREAD

**Issue by uraz** [gistia/json-log-viewer#5]
It seems that orange color used for "warn" level label is not working correctly. `{orange-fg}` is showing instead of a proper color. 

![image](https://user-images.githubusercontent.com/368871/44935162-e6cd7600-ad6f-11e8-8f0e-ac54ad203618.png)

**Comment by techieshark** [comment]
I'm seeing the same thing.

**Comment by techieshark** [comment]
@uraz You can fix this by using an RGB value for `orange` in `const levelColors = ...` in `utils.js` ([see here](https://github.com/gistia/json-log-viewer/blob/a14f0c3a65e8ac805a4c339a5f330e5f569cfcd9/src/utils.js#L95)). 

For instance, using [#FFA500](https://www.color-hex.com/color/ffa500):

change
```
const levelColors = {
  debug: s => `{cyan-fg}${s}{/cyan-fg}`,
  info: s => `{#ffff94-fg}{bold}${s}{/bold}{/#ffff94-fg}`,
  warn: s => `{orange-fg}${s}{/orange-fg}`,
  error: s => `{red-fg}${s}{/red-fg}`,
```
to 
```
const levelColors = {
  debug: s => `{cyan-fg}${s}{/cyan-fg}`,
  info: s => `{#ffff94-fg}{bold}${s}{/bold}{/#ffff94-fg}`,
  warn: s => `{#ffa500-fg}${s}{/#ffa500-fg}`,
  error: s => `{red-fg}${s}{/red-fg}`,
```

To give the following:

![image](https://user-images.githubusercontent.com/1072292/45459472-45b6b780-b6ad-11e8-8391-788d2cd57805.png)


Or if you wanted to mimic the colors used by Google Cloud's Stackdriver logging console:

<img width="206" alt="screen shot 2018-09-12 at 4 52 52 pm" src="https://user-images.githubusercontent.com/1072292/45459507-6f6fde80-b6ad-11e8-8a4f-dd980a4bc73a.png">

You could use:

```
const levelColors = {
  debug: s => `{blue-fg}${s}{/blue-fg}`,
  info: s => `{#7FDBFF-fg}${s}{/#7FDBFF-fg}`,
  warn: s => `{#DA7732-fg}${s}{/#DA7732-fg}`,
  error: s => `{#C2513F-fg}${s}{/#C2513F-fg}`,
};
```

to give:
![image](https://user-images.githubusercontent.com/1072292/45459565-b5c53d80-b6ad-11e8-808b-b94a0b6fe596.png)

In case it helps, here's my test.json file, and I'm using iTerm on Mac:
```
{ "timestamp": "2018-09-12T05:41:37.562Z", "level": "debug", "message": "message 1", "data": "some data", "another": { "any": "thing" }}
{ "timestamp": "2018-09-12T05:41:36.566Z", "level": "info", "message": "message 2", "data": "some other data" }
{ "timestamp": "2018-09-12T05:41:35.571Z", "level": "warn", "message": "message 3" }
{ "timestamp": "2018-09-12T05:41:35.571Z", "level": "error", "message": "message 4" }
{ "timestamp": "2018-09-12T05:41:35.571Z", "level": "error", "message": "message 5" }
```

**Comment by Defkil** [comment]
Hey, on npm is still the old version with {orange-fg}warn{/orange-fg}

**Comment by cube-dan** [comment]
Same problem here @Defkil (on a fresh install from today). I'm using [patch-package](https://github.com/ds300/patch-package) as a stopgap. Patch attached: [json-log-viewer+0.1.2.patch](https://github.com/gistia/json-log-viewer/files/10926835/json-log-viewer%2B0.1.2.patch)
